# Generated by Django 5.2 on 2025-04-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_medicalrecord_description_alter_medicalrecord_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('blockchain_tx', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
