# Generated by Django 5.2 on 2025-04-04 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='claim_amount',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='diagnosis_code',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='submitted_documents',
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='treatment_date',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='claim_docs/'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='treatment_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20, null=True),
        ),
    ]
