# Generated by Django 5.2 on 2025-04-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_remove_insuranceclaim_claim_amount_and_more'),
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='claims.insuranceclaim')),
            ],
        ),
        migrations.DeleteModel(
            name='FraudAnalysis',
        ),
    ]
